# -*- coding: utf-8 -*-
"""TASK-1 IRIS FLOWER CLASSIFICATION.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_OWCOu3yTrVfgTP0a1R6UT4VV3ZbfQm9

OASIS INFOBYTE INTERNSHIP

NAME: P SRI SAI SANKAR

BATCH NAME: July Phase 1 OIBSIP

TASK -1: IRIS FLOWER CLASSIFICATION using MACHINE LEARNING

OBJECTIVE:

1. Iris flower has three species: setosa,versicolor and viriginica which differs according to their measurements.
2. Our Task is to train a machine learning model that can learn from the measurements of the iris species and classify them.
"""

# import image module
from IPython.display import Image

[ ]  #to get the image
Image(url="https://machinelearninghd.com/wp-content/uploads/2021/03/iris-dataset.png",width=600, height=600)

from google.colab import files
uploaded=files.upload()

df=pd.read_csv('Iris.csv')
df.head()

df['Species'].value_counts()

df.describe()

df=df.drop(columns=['Id'])
df

from sklearn.preprocessing import LabelEncoder
species_le=LabelEncoder().fit_transform(df['Species'])
species_le

df['Species']=species_le
df

plt.scatter(df['PetalLengthCm'],df['Species'])

plt.scatter(df['PetalWidthCm'],df['Species'],c='r')
plt.scatter(df['SepalLengthCm'], df['Species'],c='g')
plt.scatter(df['SepalWidthCm'], df['Species'], c='b')
plt.xlabel('Values')
plt.ylabel('Species')
plt.show()

x=df.iloc[:,:-1].values
y=df['Species'].values
x,y

from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(x,y,test_size=0.3,random_state=42)
x_train,x_test,y_train,y_test

from sklearn.linear_model import LogisticRegression as LR
model=LR()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred,x_test

from sklearn.metrics import accuracy_score as acs
score=acs(y_test,y_pred)
score

a=model.predict(x)
b=df['Species'].values
print(a,b,sep='\n')
print(f"Accuracy={(acs(a,b)*100).__round__(2)}%")